*       Size of the camera
        edge = 1.2d+01
        corner = edge * sqrt( 2.0d+00 )

*	Ecliptic latitudes of the FOV centers of the 4 cameras
        betas( 1, 1 ) = -1.8d+01
        betas( 1, 2 ) = -4.2d+01
        betas( 1, 3 ) = -6.6d+01
        betas( 1, 4 ) = -9.0d+01
        betas( 2, 1 ) = +1.8d+01
        betas( 2, 2 ) = +4.2d+01
        betas( 2, 3 ) = +6.6d+01
        betas( 2, 4 ) = +9.0d+01

	c1limit = -5.8739d+00
        c1gap = -2.9926d+01
	c2limit = +5.8739d+00
        c1gap = +2.9926d+01
	
*       Chip gaps within camera
        gapx = 0.25d+00
	gapy = 0.25d+00

        n_c = 1
        pg_strng( 1,  1 ) = '2018-Jul-25T04:59'
        pg_strng( 1,  2 ) = '2018-Aug-22T23:49'
        pg_strng( 1,  3 ) = '2018-Sep-20T12:42'
        pg_strng( 1,  4 ) = '2018-Oct-18T13:45'
        pg_strng( 1,  5 ) = '2018-Nov-15T00:39'
        pg_strng( 1,  6 ) = '2018-Dec-11T21:34'
        pg_strng( 1,  7 ) = '2019-Jan-07T07:34'
        pg_strng( 1,  8 ) = '2019-Feb-02T09:45'
        pg_strng( 1,  9 ) = '2019-Feb-28T08:05'
        pg_strng( 1, 10 ) = '2019-Mar-26T13:52'
        pg_strng( 1, 11 ) = '2019-Apr-22T19:35'
        pg_strng( 1, 12 ) = '2019-May-21T05:34'
        pg_strng( 1, 13 ) = '2019-Jun-19T05:10'
        pg_strng( 1, 14 ) = '2019-Jul-18T00:44'

        pg_strng( 2,  1 ) = '2019-Jul-18T00:44'
        pg_strng( 2,  2 ) = '2019-Aug-15T03:48'
        pg_strng( 2,  3 ) = '2019-Sep-11T08:05'
        pg_strng( 2,  4 ) = '2019-Oct-07T14:54'
        pg_strng( 2,  5 ) = '2019-Nov-02T07:46'
        pg_strng( 2,  6 ) = '2019-Nov-27T23:04'
        pg_strng( 2,  7 ) = '2019-Dec-24T07:53'
        pg_strng( 2,  8 ) = '2020-Jan-21T02:31'
        pg_strng( 2,  9 ) = '2020-Feb-18T23:35'
        pg_strng( 2, 10 ) = '2020-Mar-18T19:50'
        pg_strng( 2, 11 ) = '2020-Apr-15T23:54'
        pg_strng( 2, 12 ) = '2020-May-13T08:33'
        pg_strng( 2, 13 ) = '2020-Jun-08T22:22'
        pg_strng( 2, 14 ) = '2020-Jul-04T22:45'
